//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGOCollection1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public System.Guid ID { get; set; }
        public string subject { get; set; }
        public string content { get; set; }
        public Nullable<short> Readcount { get; set; }
        public System.DateTime update_at { get; set; }
    }
}
