//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGOCollection1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YGOCardInfoEntities : DbContext
    {
        public YGOCardInfoEntities()
            : base("name=YGOCardInfoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Information> Information { get; set; }
        public virtual DbSet<refAttribute> refAttribute { get; set; }
        public virtual DbSet<refCardList> refCardList { get; set; }
        public virtual DbSet<refCardType> refCardType { get; set; }
        public virtual DbSet<refMonsterType> refMonsterType { get; set; }
        public virtual DbSet<refpackgroup> refpackgroup { get; set; }
        public virtual DbSet<TypeMonsterCard> TypeMonsterCard { get; set; }
        public virtual DbSet<TypeSpellCard> TypeSpellCard { get; set; }
        public virtual DbSet<TypeTrapCard> TypeTrapCard { get; set; }
        public virtual DbSet<YGOMonsters> YGOMonsters { get; set; }
        public virtual DbSet<YGOSpells> YGOSpells { get; set; }
        public virtual DbSet<YGOTraps> YGOTraps { get; set; }
    }
}
