//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YGOCollection1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class YGOMonsters
    {
        public short CardID { get; set; }
        public string CardName { get; set; }
        public Nullable<short> CardAttributeID { get; set; }
        public Nullable<short> CardLevel { get; set; }
        public Nullable<short> MonsterTypeID { get; set; }
        public Nullable<short> CardTypeID { get; set; }
        public string ATK { get; set; }
        public string DEF { get; set; }
        public Nullable<short> CardNumberID { get; set; }
        public string CardPassword { get; set; }
        public Nullable<bool> CardExtra { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
        public string CardNumber { get; set; }
        public Nullable<bool> cardenable { get; set; }

        public virtual refAttribute refAttribute { get; set; }
        public virtual refCardList refCardList { get; set; }
        public virtual refMonsterType refMonsterType { get; set; }
        public virtual TypeMonsterCard TypeMonsterCard { get; set; }
   
    }
}
